### PR TITLE
Add temperature accessor

### PR DESCRIPTION
**Pull request by rzr**
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by rzr** [comment]
This could help for:
https://www.npmjs.com/package/generic-sensors-lite

**Comment by rzr** [comment]
Hi, this project still maintained ? If not do you know any active fork ?
I planned to use this for:
 https://s-opensource.org/2018/04/25/mozilla-iot-generic-sensors/

**Comment by rzr** [comment]
Ping @jstapels @nkolban @rstets @danigoland @miniben-90 , reviews are welcome.

**Comment by rzr** [comment]
Please review, I plan to use it as alternative sensor for:

https://www.npmjs.com/package/generic-sensors-lite

**Review by rstets — APPROVED** [review]

**Pull request merged**
